### ISSUE TITLE
New as job 2

### ISSUE THREAD

**Issue by janpeterka** [janpeterka/kucharka-on-rails#32]
New as job 2

**Comment by janpeterka** [comment]
New comment

**Comment by janpeterka** [comment]
Again!

**Comment by janpeterka** [comment]
@public Oh no

**Comment by public** [comment]
🤞

**Comment by janpeterka** [comment]
@public Sorry, testing something and I didn't realize this is valid handle :sweat_smile: 
Won't happen again

**Comment by janpeterka** [comment]
#public Ok, how about this?
